name: Build and Deploy
on:
  push:
    branches:
      - master
        
jobs:
  call-base-workflow:
    uses: podkolzzzin/ResusableWorkflows/.github/workflows/base.yml@main
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello build workflow!"